### ISSUE TITLE
Generation of SLAM map

### ISSUE THREAD

**Issue by aravindSwamy94** [ieuagv/ros_ieuagv_localization#2]
Dear Team, 
     First of all, great work on this!

Few questions on this..

1. How to generate a map and give it as an input to the algorithm.

2. How the UWB coordinate system and SLAM map coordinate system are matched exactly and how do we get the final output.

Thanks in advance

**Comment by bekirbostanci** [comment]
Hi sir 
1. This repo include only localization so that you can not create map, you can only increase your robot position with uwbs sensors. This repo aim is localization. 
2. You have to placed same coordinate system with the map_server so that you can use placed your uwb in area and the control placed with rviz. After this process you can get your uwb_tag position. 

Feel free to ask any questions :)
