### ISSUE TITLE
initial pose

### ISSUE THREAD

**Issue by huyrua291996** [ieuagv/ros_ieuagv_localization#3]
Hi,
I have a question related to initial pose using uwb. Why we need to move robot 20 cm foward when we have the distances from anchors and position of anchors. If I only use kalman filter and set the initial pose (0,0,0), after numbers of loop, do the robot estimate its position.
Thanks

**Comment by scagdas** [comment]
Hi @huyrua291996 ,
It is possible to give the initial pose manually and run the Kalman filter but the reason for that first movement is to estimate the orientation of the robot. Since UWB measurements only consists of direct ranging information it is not possible to estimate the complete pose of the robot without the orientation (head angle).
